# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --black --doctest-glob="*.rst" --doctest-modules --cov=invenio_opendefinition --cov-report=term-missing
testpaths = tests invenio_opendefinition
